import gizmo

def main_program():
    print("Starting main program sequence...")
    print("-" * 20)

    gizmo.change_speed(200)
    gizmo.go_reverse(7.5)
    gizmo.go_forward(37)
    gizmo.wait_for_reflection_pick_speed(14,400)
    gizmo.go_reverse(4.2)
    gizmo.turn_left_degrees(86)
    gizmo.go_forward(5.6)
    gizmo.turn_left_degrees(28)
    gizmo.d_turn_angle(2000, 950)
    gizmo.turn_right_degrees(14)
    gizmo.go_reverse(11.5)
    gizmo.change_speed(500)
    gizmo.go_forward(5)
    gizmo.turn_right_degrees(105)
    gizmo.go_forward(7.8)
    gizmo.change_turn_speed(52)
    gizmo.turn_left_degrees(17)
    gizmo.change_speed(500)
    gizmo.go_forward(39)
