import gizmo

def main_program():
    print("Starting main program sequence...")
    print("-" * 20)


#2) Bring items to forum
    gizmo.go_forward(20)
    gizmo.go_reverse(5.1)
    gizmo.turn_right_degrees(45)
    gizmo.wait_for_reflection(14)
    gizmo.wait(200)
    gizmo.go_forward(1)
    gizmo.change_speed(400)
    gizmo.turn_right_degrees(97.8)
    gizmo.go_forward(6)
    gizmo.turn_right_degrees(50)
    gizmo.turn_left_degrees(50)
    gizmo.turn_right_degrees(50)
    gizmo.turn_left_degrees(50)
    gizmo.turn_right_degrees(50)
    gizmo.turn_left_degrees(50)
    gizmo.turn_right_degrees(50)
    gizmo.turn_left_degrees(50)
    gizmo.turn_right_degrees(50)
    gizmo.turn_left_degrees(50)
    gizmo.turn_right_degrees(50)
    gizmo.turn_left_degrees(50)
    gizmo.turn_right_degrees(50)
    gizmo.turn_left_degrees(50)
    gizmo.turn_right_degrees(50)
    gizmo.turn_left_degrees(50)
    gizmo.turn_right_degrees(50)
    gizmo.turn_left_degrees(50)
    gizmo.go_reverse(7)
    gizmo.turn_left_degrees(100)
    gizmo.change_speed(500)
    gizmo.go_reverse(36.7)

    #gizmo.go_reverse(3)
   #gizmo.go_forward(3)
    #gizmo.go_reverse(3)
    #gizmo.go_forward(3)
    #gizmo.go_reverse(3)
    #gizmo.change_turn_speed(20)
    #gizmo.turn_right_degrees(85)
    #gizmo.go_forward(10)
    #gizmo.go_reverse(9)
    #gizmo.turn_right_degrees(25.5)
    #gizmo.go_forward(27)
    #gizmo.turn_right_degrees(22.6)
    #gizmo.go_forward(9.5)
    #gizmo.d_turn_angle(1000,1800)
    #gizmo.go_reverse(9)



# --- RUN THE MAIN PROGRAM ---
#main_program()